name: 'Checkout From Tag'
author: 'EvilKittenLord'
description: 'Shallow clones a repo to the depth of the specified tag (or commit hash). Depth is auto-detected. '
branding:
  icon: settings
  color: white
inputs:
  repo:
    description: "The repository to clone."
    required: false
    default: "unset"
  ssh-token:
    description: "Required for cloning private repositories in other organizations."
    required: false
  tag:
    description: "The tag (or commit hash) to clone to."
    required: false
    default: "unset"
  dir:
    description: "The target directory to clone into."
    required: false
    default: $GITHUB_WORKSPACE
  output-depth-only:
    description: "Output the detected depth only."
    required: false
    default: "false"
outputs:
  depth:
    description: "The depth of the tag/commit."
    value: ${{ steps.main.outputs.depth }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup SSH
      if: ${{ inputs.ssh-token != '' }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< '${{ inputs.ssh-token }}'
    - name: Main Operations
      id: main
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/clone-from-tag.sh -r ${{ inputs.repo }} -t ${{ inputs.tag }} -d ${{ inputs.dir }} -o ${{ inputs.output-depth-only }}
        echo "depth=$(cat /tmp/tag_depth)" | tee $GITHUB_OUTPUT