name: 'Checkout From Tag'
author: 'EvilKittenLord'
description: 'Shallow clones a repo to the depth of the specified tag (or commit hash). Depth is auto-detected. '
branding:
  icon: settings
  color: white
inputs:
  repo:
    description: "The repository to clone."
    required: false
    default: "https://github.com/${{ github.repository }}.git"
  ssh-token:
    description: "Required for cloning private repositories in other organizations."
    required: false
  tag:
    description: "The tag (or commit hash) to clone to."
    required: false
    default: 'unset'
  dir:
    description: "The target directory to clone into."
    requied: false
    default: $GITHUB_WORKSPACE
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Shallow Clone
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        [[ -n ${{ inputs.ssh-token }} ]] && ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        [[ -n ${{ inputs.ssh-token }} ]] && ssh-add - <<< '${{ inputs.ssh-token }}'
        ${{ github.action_path }}/scripts/clone-from-tag.sh -r ${{ inputs.repo }} -t ${{ inputs.tag }} -d ${{ inputs.dir }}
      shell: bash
