name: Validate Checkout From Tag - No Inputs

on:
  workflow_dispatch:

jobs:
  use-action:
    name: Checkout From Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github-actions-gitops-autover to the depth of the last DETECTED version
      uses: AlexAtkinson/github-action-checkout-from-tag@latest
    - name: Verify Checkout
      run: |
        git log --pretty=oneline --decorate=full
