name: Validate Checkout From Tag

on:
  workflow_dispatch:

jobs:
  use-action:
    name: Checkout From Tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout github-actions-gitops-autover to the depth of tag 0.1.6
      uses: AlexAtkinson/github-action-checkout-from-tag@latest
      with:
        repo: https://github.com/AlexAtkinson/github-action-gitops-autover.git
        tag: 0.1.6
        dir: foo_bar1
    - name: Verify Checkout
      run: |
        cd foo_bar1
        git log --tags --pretty=oneline --decorate=full
    - name: Checkout github-actions-gitops-autover to the depth of tag 0.1.3
      uses: AlexAtkinson/github-action-checkout-from-tag@latest
      with:
        repo: https://github.com/AlexAtkinson/github-action-gitops-autover.git
        tag: 0.1.3
        dir: foo_bar2
    - name: Verify Checkout
      run: |
        cd foo_bar2
        git log --tags --pretty=oneline --decorate=full